name = "MultiAgentPOMDPs"
uuid = "9ac5fd70-7902-42e7-9745-ff446b44e779"
authors = ["rejuvyesh <mail@rejuvyesh.com>, Shushman <shushmanchoudhary@gmail.com> and contributors"]
version = "0.1.0"

[deps]
POMDPs = "a93abf59-7444-517b-a68a-c42f96afdd7d"

[compat]
POMDPs = "0.9"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
