name = "MultiAgentPOMDPs"
uuid = "9ac5fd70-7902-42e7-9745-ff446b44e779"
authors = ["rejuvyesh <mail@rejuvyesh.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
